package kr.ac.kaist.jiset.js

import kr.ac.kaist.jiset.spec.algorithm._
import kr.ac.kaist.jiset.ir._
import scala.collection.mutable.{ Map => MMap }

object BaseModel {
  lazy val globals: Map[String, Value] = Map(
    ALGORITHM -> NamedAddr(ALGORITHM),
    CONTEXT -> Null,
    EXECUTION_STACK -> NamedAddr(EXECUTION_STACK),
    GLOBAL -> NamedAddr(GLOBAL),
    HOST_DEFINED -> Undef,
    INTRINSICS -> NamedAddr(INTRINSICS),
    JOB_QUEUE -> NamedAddr(JOB_QUEUE),
    PRIMITIVE -> NamedAddr(PRIMITIVE),
    REALM -> NamedAddr(REALM),
    RESULT -> NormalComp(Absent),
    RET_CONT -> Undef,
    SYMBOL_REGISTRY -> NamedAddr(SYMBOL_REGISTRY),
    "Number" -> Str("Number"),
    "BigInt" -> Str("BigInt"),
    "Undefined" -> Str("Undefined"),
    "Null" -> Str("Null"),
    "String" -> Str("String"),
    "Boolean" -> Str("Boolean"),
    "Symbol" -> Str("Symbol"),
    "Reference" -> Str("Reference"),
    "Object" -> Str("Object"),
  )

  lazy val heap: Map[Addr, Obj] = builtin.Heap.map ++ Map(
    NamedAddr(ALGORITHM) -> IRMap(ALGORITHM)(Nil),
    NamedAddr(INTRINSICS) -> IRMap(INTRINSICS)(Nil),
    NamedAddr(EXECUTION_STACK) -> IRList(),
    NamedAddr(JOB_QUEUE) -> IRList(),
    NamedAddr(PRIMITIVE) -> IRMap(PRIMITIVE)(List(
      Str("Number") -> NamedAddr(PRIMITIVE + ".Number"),
      Str("BigInt") -> NamedAddr(PRIMITIVE + ".BigInt"),
    )),
    NamedAddr(PRIMITIVE + ".Number") -> IRMap("Record")(List(
      Str("unit") -> Num(1),
      Str("unaryMinus") -> Func(algoMap("Number::unaryMinus")),
      Str("bitwiseNOT") -> Func(algoMap("Number::bitwiseNOT")),
      Str("exponentiate") -> Func(algoMap("Number::exponentiate")),
      Str("multiply") -> Func(algoMap("Number::multiply")),
      Str("divide") -> Func(algoMap("Number::divide")),
      Str("remainder") -> Func(algoMap("Number::remainder")),
      Str("add") -> Func(algoMap("Number::add")),
      Str("subtract") -> Func(algoMap("Number::subtract")),
      Str("leftShift") -> Func(algoMap("Number::leftShift")),
      Str("signedRightShift") -> Func(algoMap("Number::signedRightShift")),
      Str("unsignedRightShift") -> Func(algoMap("Number::unsignedRightShift")),
      Str("lessThan") -> Func(algoMap("Number::lessThan")),
      Str("equal") -> Func(algoMap("Number::equal")),
      Str("sameValue") -> Func(algoMap("Number::sameValue")),
      Str("sameValueZero") -> Func(algoMap("Number::sameValueZero")),
      Str("bitwiseAND") -> Func(algoMap("Number::bitwiseAND")),
      Str("bitwiseXOR") -> Func(algoMap("Number::bitwiseXOR")),
      Str("bitwiseOR") -> Func(algoMap("Number::bitwiseOR")),
      Str("toString") -> Func(algoMap("Number::toString")),
    )),
    NamedAddr(PRIMITIVE + ".BigInt") -> IRMap("Record")(List(
      Str("unit") -> BigINum(1),
      Str("unaryMinus") -> Func(algoMap("BigInt::unaryMinus")),
      Str("bitwiseNOT") -> Func(algoMap("BigInt::bitwiseNOT")),
      Str("exponentiate") -> Func(algoMap("BigInt::exponentiate")),
      Str("multiply") -> Func(algoMap("BigInt::multiply")),
      Str("divide") -> Func(algoMap("BigInt::divide")),
      Str("remainder") -> Func(algoMap("BigInt::remainder")),
      Str("add") -> Func(algoMap("BigInt::add")),
      Str("subtract") -> Func(algoMap("BigInt::subtract")),
      Str("leftShift") -> Func(algoMap("BigInt::leftShift")),
      Str("signedRightShift") -> Func(algoMap("BigInt::signedRightShift")),
      Str("unsignedRightShift") -> Func(algoMap("BigInt::unsignedRightShift")),
      Str("lessThan") -> Func(algoMap("BigInt::lessThan")),
      Str("equal") -> Func(algoMap("BigInt::equal")),
      Str("sameValue") -> Func(algoMap("BigInt::sameValue")),
      Str("sameValueZero") -> Func(algoMap("BigInt::sameValueZero")),
      Str("bitwiseAND") -> Func(algoMap("BigInt::bitwiseAND")),
      Str("bitwiseXOR") -> Func(algoMap("BigInt::bitwiseXOR")),
      Str("bitwiseOR") -> Func(algoMap("BigInt::bitwiseOR")),
      Str("toString") -> Func(algoMap("BigInt::toString")),
    )),
    NamedAddr(SYMBOL_REGISTRY) -> IRList(),
  )
}
