            1. Let _A_ be a set of characters containing the sixty-three characters:
            <figure>
              <table class="lightweight-table">
                <tbody>
                  <tr>
                    <td>
                      `a`
                    </td>
                    <td>
                      `b`
                    </td>
                    <td>
                      `c`
                    </td>
                    <td>
                      `d`
                    </td>
                    <td>
                      `e`
                    </td>
                    <td>
                      `f`
                    </td>
                    <td>
                      `g`
                    </td>
                    <td>
                      `h`
                    </td>
                    <td>
                      `i`
                    </td>
                    <td>
                      `j`
                    </td>
                    <td>
                      `k`
                    </td>
                    <td>
                      `l`
                    </td>
                    <td>
                      `m`
                    </td>
                    <td>
                      `n`
                    </td>
                    <td>
                      `o`
                    </td>
                    <td>
                      `p`
                    </td>
                    <td>
                      `q`
                    </td>
                    <td>
                      `r`
                    </td>
                    <td>
                      `s`
                    </td>
                    <td>
                      `t`
                    </td>
                    <td>
                      `u`
                    </td>
                    <td>
                      `v`
                    </td>
                    <td>
                      `w`
                    </td>
                    <td>
                      `x`
                    </td>
                    <td>
                      `y`
                    </td>
                    <td>
                      `z`
                    </td>
                  </tr>
                  <tr>
                    <td>
                      `A`
                    </td>
                    <td>
                      `B`
                    </td>
                    <td>
                      `C`
                    </td>
                    <td>
                      `D`
                    </td>
                    <td>
                      `E`
                    </td>
                    <td>
                      `F`
                    </td>
                    <td>
                      `G`
                    </td>
                    <td>
                      `H`
                    </td>
                    <td>
                      `I`
                    </td>
                    <td>
                      `J`
                    </td>
                    <td>
                      `K`
                    </td>
                    <td>
                      `L`
                    </td>
                    <td>
                      `M`
                    </td>
                    <td>
                      `N`
                    </td>
                    <td>
                      `O`
                    </td>
                    <td>
                      `P`
                    </td>
                    <td>
                      `Q`
                    </td>
                    <td>
                      `R`
                    </td>
                    <td>
                      `S`
                    </td>
                    <td>
                      `T`
                    </td>
                    <td>
                      `U`
                    </td>
                    <td>
                      `V`
                    </td>
                    <td>
                      `W`
                    </td>
                    <td>
                      `X`
                    </td>
                    <td>
                      `Y`
                    </td>
                    <td>
                      `Z`
                    </td>
                  </tr>
                  <tr>
                    <td>
                      `0`
                    </td>
                    <td>
                      `1`
                    </td>
                    <td>
                      `2`
                    </td>
                    <td>
                      `3`
                    </td>
                    <td>
                      `4`
                    </td>
                    <td>
                      `5`
                    </td>
                    <td>
                      `6`
                    </td>
                    <td>
                      `7`
                    </td>
                    <td>
                      `8`
                    </td>
                    <td>
                      `9`
                    </td>
                    <td>
                      `_`
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                    <td>
                    </td>
                  </tr>
                </tbody>
              </table>
            </figure>
            1. Let _U_ be an empty set.
            1. For each character _c_ not in set _A_ where Canonicalize(_c_) is in _A_, add _c_ to _U_.
            1. Assert: Unless _Unicode_ and _IgnoreCase_ are both *true*, _U_ is empty.
            1. Add the characters in set _U_ to set _A_.
            1. Return _A_.