package kr.ac.kaist.jiset.editor

import kr.ac.kaist.jiset.js.ast._
import kr.ac.kaist.jiset.util.Span

object SyntacticViewSeed {

  val syntacticViewSeed: List[SyntacticView] = List(
    ArrayLiteral2(AbsElementList, Some(AbsElision), List(false, false), Span()),
    ArrayLiteral2(AbsElementList, None, List(false, false), Span()),
    MemberExpression1(AbsMemberExpression, AbsExpression, List(false, false), Span()),
    MemberExpression3(AbsMemberExpression, AbsTemplateLiteral, List(false, false), Span()),
    MemberExpression6(AbsMemberExpression, AbsArguments, List(false, false), Span()),
    CallExpression3(AbsCallExpression, AbsArguments, List(false, false), Span()),
    CallExpression4(AbsCallExpression, AbsExpression, List(false, false), Span()),
    CallExpression6(AbsCallExpression, AbsTemplateLiteral, List(false, false), Span()),
    OptionalExpression0(AbsMemberExpression, AbsOptionalChain, List(false, false), Span()),
    OptionalExpression1(AbsCallExpression, AbsOptionalChain, List(false, false), Span()),
    OptionalExpression2(AbsOptionalExpression, AbsOptionalChain, List(false, false), Span()),
    ExponentiationExpression1(AbsUpdateExpression, AbsExponentiationExpression, List(false, false), Span()),
    MultiplicativeExpression1(AbsMultiplicativeExpression, AbsMultiplicativeOperator, AbsExponentiationExpression, List(false, false), Span()),
    AdditiveExpression1(AbsAdditiveExpression, AbsMultiplicativeExpression, List(false, false), Span()),
    AdditiveExpression2(AbsAdditiveExpression, AbsMultiplicativeExpression, List(false, false), Span()),
    ShiftExpression1(AbsShiftExpression, AbsAdditiveExpression, List(false, false), Span()),
    ShiftExpression2(AbsShiftExpression, AbsAdditiveExpression, List(false, false), Span()),
    ShiftExpression3(AbsShiftExpression, AbsAdditiveExpression, List(false, false), Span()),
    RelationalExpression1(AbsRelationalExpression, AbsShiftExpression, List(false, false, false), Span()),
    RelationalExpression2(AbsRelationalExpression, AbsShiftExpression, List(false, false, false), Span()),
    RelationalExpression3(AbsRelationalExpression, AbsShiftExpression, List(false, false, false), Span()),
    RelationalExpression4(AbsRelationalExpression, AbsShiftExpression, List(false, false, false), Span()),
    RelationalExpression5(AbsRelationalExpression, AbsShiftExpression, List(false, false, false), Span()),
    RelationalExpression6(AbsRelationalExpression, AbsShiftExpression, List(false, false, false), Span()),
    EqualityExpression1(AbsEqualityExpression, AbsRelationalExpression, List(false, false, false), Span()),
    EqualityExpression2(AbsEqualityExpression, AbsRelationalExpression, List(false, false, false), Span()),
    EqualityExpression3(AbsEqualityExpression, AbsRelationalExpression, List(false, false, false), Span()),
    EqualityExpression4(AbsEqualityExpression, AbsRelationalExpression, List(false, false, false), Span()),
    BitwiseANDExpression1(AbsBitwiseANDExpression, AbsEqualityExpression, List(false, false, false), Span()),
    BitwiseXORExpression1(AbsBitwiseXORExpression, AbsBitwiseANDExpression, List(false, false, false), Span()),
    BitwiseORExpression1(AbsBitwiseORExpression, AbsBitwiseXORExpression, List(false, false, false), Span()),
    LogicalANDExpression1(AbsLogicalANDExpression, AbsBitwiseORExpression, List(false, false, false), Span()),
    LogicalORExpression1(AbsLogicalORExpression, AbsLogicalANDExpression, List(false, false, false), Span()),
    CoalesceExpression0(AbsCoalesceExpressionHead, AbsBitwiseORExpression, List(false, false, false), Span()),
    ConditionalExpression1(AbsShortCircuitExpression, AbsAssignmentExpression, AbsAssignmentExpression, List(false, false, false), Span()),
    AssignmentExpression4(AbsLeftHandSideExpression, AbsAssignmentExpression, List(false, false, false), Span()),
    AssignmentExpression5(AbsLeftHandSideExpression, AbsAssignmentOperator, AbsAssignmentExpression, List(false, false, false), Span()),
    AssignmentExpression6(AbsLeftHandSideExpression, AbsAssignmentExpression, List(false, false, false), Span()),
    AssignmentExpression7(AbsLeftHandSideExpression, AbsAssignmentExpression, List(false, false, false), Span()),
    AssignmentExpression8(AbsLeftHandSideExpression, AbsAssignmentExpression, List(false, false, false), Span()),
    Expression1(AbsExpression, AbsAssignmentExpression, List(false, false, false), Span()),
    StatementList1(AbsStatementList, AbsStatementListItem, List(false, false, false), Span()),
    LexicalDeclaration0(AbsLetOrConst, AbsBindingList, List(false, false, false), Span()),
    BindingList1(AbsBindingList, AbsLexicalBinding, List(false, false, false), Span()),
    LexicalBinding0(AbsBindingIdentifier, Some(AbsInitializer), List(false, false, false), Span()),
    LexicalBinding0(AbsBindingIdentifier, None, List(false, false, false), Span()),
    LexicalBinding1(AbsBindingPattern, AbsInitializer, List(false, false, false), Span()),
    VariableDeclarationList1(AbsVariableDeclarationList, AbsVariableDeclaration, List(false, false, false), Span()),
    VariableDeclaration0(AbsBindingIdentifier, Some(AbsInitializer), List(false, false, false), Span()),
    VariableDeclaration0(AbsBindingIdentifier, None, List(false, false, false), Span()),
    VariableDeclaration1(AbsBindingPattern, AbsInitializer, List(false, false, false), Span()),
    IfStatement0(AbsExpression, AbsStatement, AbsStatement, List(false, false, false), Span()),
    IfStatement1(AbsExpression, AbsStatement, List(false, false, false), Span()),
    WithStatement0(AbsExpression, AbsStatement, List(false, false, false), Span()),
    SwitchStatement0(AbsExpression, AbsCaseBlock, List(false, false, false), Span()),
    CaseClause0(AbsExpression, Some(AbsStatementList), List(false, false, false), Span()),
    CaseClause0(AbsExpression, None, List(false, false, false), Span()),
    LabelledStatement0(AbsLabelIdentifier, AbsLabelledItem, List(false, false, false), Span()),
    TryStatement0(AbsBlock, AbsCatch, List(false, false, false), Span()),
    TryStatement1(AbsBlock, AbsFinally, List(false, false, false), Span()),
    TryStatement2(AbsBlock, AbsCatch, AbsFinally, List(false, false, false), Span()),
    FunctionDeclaration0(AbsBindingIdentifier, AbsFormalParameters, AbsFunctionBody, List(false, false, false), Span()),
    FunctionDeclaration1(AbsFormalParameters, AbsFunctionBody, List(false, false, false), Span()),
    FunctionExpression0(Some(AbsBindingIdentifier), AbsFormalParameters, AbsFunctionBody, List(), Span()),
    FunctionExpression0(None, AbsFormalParameters, AbsFunctionBody, List(), Span()),
    ArrowFunction0(AbsArrowParameters, AbsConciseBody, List(false, false, false), Span()),
    GeneratorExpression0(Some(AbsBindingIdentifier), AbsFormalParameters, AbsGeneratorBody, List(), Span()),
    GeneratorExpression0(None, AbsFormalParameters, AbsGeneratorBody, List(), Span()),
    AsyncGeneratorExpression0(Some(AbsBindingIdentifier), AbsFormalParameters, AbsAsyncGeneratorBody, List(), Span()),
    AsyncGeneratorExpression0(None, AbsFormalParameters, AbsAsyncGeneratorBody, List(), Span()),
    ClassDeclaration0(AbsBindingIdentifier, AbsClassTail, List(false, false, false), Span()),
    ClassExpression0(Some(AbsBindingIdentifier), AbsClassTail, List(false, false), Span()),
    ClassExpression0(None, AbsClassTail, List(false, false), Span()),
    AsyncFunctionDeclaration0(AbsBindingIdentifier, AbsFormalParameters, AbsAsyncFunctionBody, List(false, false, false), Span()),
    AsyncFunctionDeclaration1(AbsFormalParameters, AbsAsyncFunctionBody, List(false, false, false), Span()),
    AsyncFunctionExpression0(Some(AbsBindingIdentifier), AbsFormalParameters, AbsAsyncFunctionBody, List(), Span()),
    AsyncFunctionExpression0(None, AbsFormalParameters, AbsAsyncFunctionBody, List(), Span()),
    AsyncArrowFunction0(AbsAsyncArrowBindingIdentifier, AbsAsyncConciseBody, List(false, false, false), Span()),
    AsyncArrowFunction1(AbsCoverCallExpressionAndAsyncArrowHead, AbsAsyncConciseBody, List(false, false, false), Span()),
    ModuleItemList1(AbsModuleItemList, AbsModuleItem, List(), Span()),
    ExportDeclaration0(AbsExportFromClause, AbsFromClause, List(), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList5(AbsExpression, AbsBindingIdentifier, List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList6(AbsExpression, AbsBindingPattern, List(false, false), Span()), List(false, false), Span()),
    ArrayLiteral1(ElementList0(Some(AbsElision), AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()),
    ArrayLiteral1(ElementList0(None, AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()),
    ArrayLiteral1(ElementList1(Some(AbsElision), AbsSpreadElement, List(false, false), Span()), List(false, false), Span()),
    ArrayLiteral1(ElementList1(None, AbsSpreadElement, List(false, false), Span()), List(false, false), Span()),
    ArrayLiteral1(ElementList2(AbsElementList, Some(AbsElision), AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()),
    ArrayLiteral1(ElementList2(AbsElementList, None, AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()),
    ArrayLiteral1(ElementList3(AbsElementList, Some(AbsElision), AbsSpreadElement, List(false, false), Span()), List(false, false), Span()),
    ArrayLiteral1(ElementList3(AbsElementList, None, AbsSpreadElement, List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral1(PropertyDefinitionList1(AbsPropertyDefinitionList, AbsPropertyDefinition, List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList1(AbsPropertyDefinitionList, AbsPropertyDefinition, List(false, false), Span()), List(false, false), Span()),
    HoistableDeclaration1(GeneratorDeclaration0(AbsBindingIdentifier, AbsFormalParameters, AbsGeneratorBody, List(false, false, false), Span()), List(false, false, false), Span()),
    HoistableDeclaration1(GeneratorDeclaration1(AbsFormalParameters, AbsGeneratorBody, List(false, false, false), Span()), List(false, false, false), Span()),
    HoistableDeclaration3(AsyncGeneratorDeclaration0(AbsBindingIdentifier, AbsFormalParameters, AbsAsyncGeneratorBody, List(false, false, false), Span()), List(false, false, false), Span()),
    HoistableDeclaration3(AsyncGeneratorDeclaration1(AbsFormalParameters, AbsAsyncGeneratorBody, List(false, false, false), Span()), List(false, false, false), Span()),
    CallExpression0(CoverCallExpressionAndAsyncArrowHead0(AbsMemberExpression, AbsArguments, List(false, false), Span()), List(false, false), Span()),
    ModuleItem0(ImportDeclaration0(AbsImportClause, AbsFromClause, List(), Span()), List(), Span()),
    ObjectLiteral1(PropertyDefinitionList0(PropertyDefinition2(AbsPropertyName, AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList0(PropertyDefinition2(AbsPropertyName, AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    SuperCall0(Arguments1(ArgumentList2(AbsArgumentList, AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    SuperCall0(Arguments2(ArgumentList2(AbsArgumentList, AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    SuperCall0(Arguments1(ArgumentList3(AbsArgumentList, AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    SuperCall0(Arguments2(ArgumentList3(AbsArgumentList, AbsAssignmentExpression, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    BreakableStatement0(IterationStatement0(DoWhileStatement0(AbsStatement, AbsExpression, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement1(WhileStatement0(AbsExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement0(Some(AbsExpression), Some(AbsExpression), Some(AbsExpression), AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement0(Some(AbsExpression), Some(AbsExpression), None, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement0(Some(AbsExpression), None, Some(AbsExpression), AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement0(Some(AbsExpression), None, None, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement0(None, Some(AbsExpression), Some(AbsExpression), AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement0(None, Some(AbsExpression), None, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement0(None, None, Some(AbsExpression), AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement0(None, None, None, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement1(AbsVariableDeclarationList, Some(AbsExpression), Some(AbsExpression), AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement1(AbsVariableDeclarationList, Some(AbsExpression), None, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement1(AbsVariableDeclarationList, None, Some(AbsExpression), AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement1(AbsVariableDeclarationList, None, None, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement2(AbsLexicalDeclaration, Some(AbsExpression), Some(AbsExpression), AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement2(AbsLexicalDeclaration, Some(AbsExpression), None, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement2(AbsLexicalDeclaration, None, Some(AbsExpression), AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement2(ForStatement2(AbsLexicalDeclaration, None, None, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement0(AbsLeftHandSideExpression, AbsExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement1(AbsForBinding, AbsExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement2(AbsForDeclaration, AbsExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement3(AbsLeftHandSideExpression, AbsAssignmentExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement4(AbsForBinding, AbsAssignmentExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement5(AbsForDeclaration, AbsAssignmentExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement6(AbsLeftHandSideExpression, AbsAssignmentExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement7(AbsForBinding, AbsAssignmentExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    BreakableStatement0(IterationStatement3(ForInOfStatement8(AbsForDeclaration, AbsAssignmentExpression, AbsStatement, List(false, false, false), Span()), List(false, false, false), Span()), List(false, false, false), Span()),
    ExportDeclaration5(ClassDeclaration1(ClassTail0(Some(AbsClassHeritage), Some(AbsClassBody), List(false, false), Span()), List(false, false, false), Span()), List(), Span()),
    ExportDeclaration5(ClassDeclaration1(ClassTail0(Some(AbsClassHeritage), None, List(false, false), Span()), List(false, false, false), Span()), List(), Span()),
    ExportDeclaration5(ClassDeclaration1(ClassTail0(None, Some(AbsClassBody), List(false, false), Span()), List(false, false, false), Span()), List(), Span()),
    ExportDeclaration5(ClassDeclaration1(ClassTail0(None, None, List(false, false), Span()), List(false, false, false), Span()), List(), Span()),
    ExportDeclaration1(NamedExports1(ExportsList1(AbsExportsList, AbsExportSpecifier, List(), Span()), List(), Span()), List(), Span()),
    ExportDeclaration1(NamedExports2(ExportsList1(AbsExportsList, AbsExportSpecifier, List(), Span()), List(), Span()), List(), Span()),
    ObjectLiteral1(PropertyDefinitionList0(PropertyDefinition1(CoverInitializedName0(AbsIdentifierReference, AbsInitializer, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList0(PropertyDefinition1(CoverInitializedName0(AbsIdentifierReference, AbsInitializer, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern0(ObjectBindingPattern3(AbsBindingPropertyList, Some(AbsBindingRestProperty), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern0(ObjectBindingPattern3(AbsBindingPropertyList, None, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern0(Some(AbsElision), Some(AbsBindingRestElement), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern0(Some(AbsElision), None, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern0(None, Some(AbsBindingRestElement), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern0(None, None, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern2(AbsBindingElementList, Some(AbsElision), Some(AbsBindingRestElement), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern2(AbsBindingElementList, Some(AbsElision), None, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern2(AbsBindingElementList, None, Some(AbsBindingRestElement), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern2(AbsBindingElementList, None, None, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral1(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition0(AbsPropertyName, AbsUniqueFormalParameters, AbsFunctionBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition0(AbsPropertyName, AbsUniqueFormalParameters, AbsFunctionBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral1(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition4(AbsPropertyName, AbsFunctionBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition4(AbsPropertyName, AbsFunctionBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral1(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition5(AbsPropertyName, AbsPropertySetParameterList, AbsFunctionBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition5(AbsPropertyName, AbsPropertySetParameterList, AbsFunctionBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ExportDeclaration3(Declaration1(ClassDeclaration1(ClassTail0(Some(AbsClassHeritage), Some(AbsClassBody), List(false, false), Span()), List(false, false, false), Span()), List(false, false), Span()), List(), Span()),
    ExportDeclaration3(Declaration1(ClassDeclaration1(ClassTail0(Some(AbsClassHeritage), None, List(false, false), Span()), List(false, false, false), Span()), List(false, false), Span()), List(), Span()),
    ExportDeclaration3(Declaration1(ClassDeclaration1(ClassTail0(None, Some(AbsClassBody), List(false, false), Span()), List(false, false, false), Span()), List(false, false), Span()), List(), Span()),
    ExportDeclaration3(Declaration1(ClassDeclaration1(ClassTail0(None, None, List(false, false), Span()), List(false, false, false), Span()), List(false, false), Span()), List(), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern0(ObjectBindingPattern2(BindingPropertyList1(AbsBindingPropertyList, AbsBindingProperty, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern1(BindingElementList1(AbsBindingElementList, AbsBindingElisionElement, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral1(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition1(GeneratorMethod0(AbsPropertyName, AbsUniqueFormalParameters, AbsGeneratorBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition1(GeneratorMethod0(AbsPropertyName, AbsUniqueFormalParameters, AbsGeneratorBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral1(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition3(AsyncGeneratorMethod0(AbsPropertyName, AbsUniqueFormalParameters, AbsAsyncGeneratorBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition3(AsyncGeneratorMethod0(AbsPropertyName, AbsUniqueFormalParameters, AbsAsyncGeneratorBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral1(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition2(AsyncMethod0(AbsPropertyName, AbsUniqueFormalParameters, AbsAsyncFunctionBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ObjectLiteral2(PropertyDefinitionList0(PropertyDefinition3(MethodDefinition2(AsyncMethod0(AbsPropertyName, AbsUniqueFormalParameters, AbsAsyncFunctionBody, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern1(BindingElementList0(BindingElisionElement0(Some(AbsElision), AbsBindingElement, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern1(ArrayBindingPattern1(BindingElementList0(BindingElisionElement0(None, AbsBindingElement, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern0(ObjectBindingPattern2(BindingPropertyList0(BindingProperty1(AbsPropertyName, AbsBindingElement, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern0(ObjectBindingPattern2(BindingPropertyList0(BindingProperty0(SingleNameBinding0(AbsBindingIdentifier, Some(AbsInitializer), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    PrimaryExpression12(CoverParenthesizedExpressionAndArrowParameterList4(BindingPattern0(ObjectBindingPattern2(BindingPropertyList0(BindingProperty0(SingleNameBinding0(AbsBindingIdentifier, None, List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()), List(false, false), Span()),
    ModuleBody0(ModuleItemList0(ModuleItem2(StatementListItem1(Declaration1(ClassDeclaration1(ClassTail0(Some(AbsClassHeritage), Some(AbsClassBody), List(false, false), Span()), List(false, false, false), Span()), List(false, false), Span()), List(false, false, false), Span()), List(), Span()), List(), Span()), List(), Span()),
    ModuleBody0(ModuleItemList0(ModuleItem2(StatementListItem1(Declaration1(ClassDeclaration1(ClassTail0(Some(AbsClassHeritage), None, List(false, false), Span()), List(false, false, false), Span()), List(false, false), Span()), List(false, false, false), Span()), List(), Span()), List(), Span()), List(), Span()),
    ModuleBody0(ModuleItemList0(ModuleItem2(StatementListItem1(Declaration1(ClassDeclaration1(ClassTail0(None, Some(AbsClassBody), List(false, false), Span()), List(false, false, false), Span()), List(false, false), Span()), List(false, false, false), Span()), List(), Span()), List(), Span()), List(), Span()),
    ModuleBody0(ModuleItemList0(ModuleItem2(StatementListItem1(Declaration1(ClassDeclaration1(ClassTail0(None, None, List(false, false), Span()), List(false, false, false), Span()), List(false, false), Span()), List(false, false, false), Span()), List(), Span()), List(), Span()), List(), Span()),
  ).map(SyntacticView)

}
